from __future__ import annotations

import json
from pathlib import Path

import pytest
import requests
from click.testing import CliRunner

from localmw.cli import cli
from localmw.codesearch import USER_AGENT, CodesearchClient, CodesearchError, RepoResult

REVISION = "a" * 40


class FakeResponse:
    def __init__(self, payload=None, status_code: int = 200, text: str | None = None):
        self.status_code = status_code
        self.text = text if text is not None else json.dumps(payload)

    def json(self):
        return json.loads(self.text)


class FakeSession:
    def __init__(self, *responses):
        self.responses = list(responses)
        self.calls = []
        self.headers = {}
        self.raises = None

    def get(self, url, params=None, timeout=None):
        self.calls.append({"url": url, "params": params})
        if self.raises is not None:
            raise self.raises
        return self.responses.pop(0)


def line(text: str, number: int, before=(), after=()) -> dict:
    return {"Line": text, "LineNumber": number, "Before": list(before), "After": list(after)}


def repo_payload(*files: tuple[str, list[dict]], files_with_match: int | None = None) -> dict:
    return {
        "Matches": [{"Filename": name, "Matches": lines, "AutoGenerated": False} for name, lines in files],
        "FilesWithMatch": files_with_match if files_with_match is not None else len(files),
        "Revision": REVISION,
    }


RESULTS = {
    "Results": {
        "Extension:Echo": repo_payload(("includes/Hooks.php", [line("$x = getUserBlock();", 12)])),
        "Other/thing": repo_payload(("src/a.js", [line("getUserBlock()", 3)])),
        "MediaWiki core": repo_payload(
            ("includes/Setup.php", [line("getUserBlock( $u );", 40, before=["// a"], after=["// b"])]),
            files_with_match=3,
        ),
    }
}


# -- client -----------------------------------------------------------------


def test_search_parses_and_orders_results():
    session = FakeSession(FakeResponse(RESULTS))
    client = CodesearchClient("https://codesearch.example.org/", session=session)
    results = client.search("search", client.params("getUserBlock", ignore_case=True, context=1, max_files=5))

    assert session.calls[0]["url"] == "https://codesearch.example.org/search/api/v1/search"
    params = session.calls[0]["params"]
    assert params["q"] == "getUserBlock"
    assert params["i"] == "fosho"
    assert params["ctx"] == "1"
    assert params["rng"] == ":5"
    assert session.headers["User-Agent"] == USER_AGENT

    assert [result.repo for result in results] == ["MediaWiki core", "Extension:Echo", "Other/thing"]
    core = results[0]
    assert core.files_with_match == 3
    assert core.files[0].lines[0].before == ["// a"]


def test_a_bad_regex_is_reported():
    session = FakeSession(FakeResponse({"Error": "error parsing regexp: missing closing )"}))
    with pytest.raises(CodesearchError, match="missing closing"):
        CodesearchClient(session=session).search("search", CodesearchClient.params("("))


def test_a_non_json_response_is_reported():
    session = FakeSession(FakeResponse(text="<html>nope</html>"))
    with pytest.raises(CodesearchError, match="is 'nosuch' a Codesearch backend"):
        CodesearchClient(session=session).search("nosuch", CodesearchClient.params("x"))


def test_http_errors_are_reported():
    session = FakeSession(FakeResponse({}, status_code=502))
    with pytest.raises(CodesearchError, match="HTTP 502"):
        CodesearchClient(session=session).search("search", CodesearchClient.params("x"))


def test_network_errors_are_reported():
    session = FakeSession()
    session.raises = requests.ConnectionError("boom")
    with pytest.raises(CodesearchError, match="could not reach"):
        CodesearchClient(session=session).search("search", CodesearchClient.params("x"))


@pytest.mark.parametrize(
    ("repo", "rel", "url"),
    [
        ("MediaWiki core", ".", f"https://gerrit.wikimedia.org/g/mediawiki/core/+/{REVISION}/a.php#7"),
        (
            "Extension:Echo",
            "extensions/Echo",
            f"https://gerrit.wikimedia.org/g/mediawiki/extensions/Echo/+/{REVISION}/a.php#7",
        ),
        ("Skin:Vector", "skins/Vector", f"https://gerrit.wikimedia.org/g/mediawiki/skins/Vector/+/{REVISION}/a.php#7"),
        ("Other/thing", None, None),
    ],
)
def test_mediawiki_repositories_map_to_a_local_path_and_gitiles(repo, rel, url):
    result = RepoResult(repo=repo, revision=REVISION, files_with_match=0, files=[])
    assert result.local_rel_path == rel
    assert result.file_url("a.php", 7) == url


def test_ui_url_reproduces_the_search():
    client = CodesearchClient("https://codesearch.example.org")
    url = client.ui_url("core", client.params("a b", files=r"\.php$"))
    assert url.startswith("https://codesearch.example.org/core/?q=a+b&files=%5C.php%24")


# -- command ----------------------------------------------------------------


@pytest.fixture
def session(monkeypatch) -> FakeSession:
    fake = FakeSession(FakeResponse(RESULTS))
    monkeypatch.setattr(CodesearchClient, "_get_session", lambda self: fake)
    return fake


@pytest.fixture
def invoke(config_dir: Path):
    def _invoke(*args: str):
        return CliRunner().invoke(cli, list(args), catch_exceptions=False)

    return _invoke


def test_command_prints_matches_grouped_by_repository(invoke, session):
    result = invoke("codesearch", "-C", "1", "getUserBlock")
    assert result.exit_code == 0
    assert session.calls[0]["params"]["ctx"] == "1"
    assert result.output.index("MediaWiki core") < result.output.index("Extension:Echo")
    assert "includes/Setup.php" in result.output
    assert "40  getUserBlock( $u );" in result.output
    assert "39  // a" in result.output
    assert "+2 more files" in result.output
    assert "3 matches · 3 files · 3 repositories" in result.output


def test_command_joins_words_and_escapes_fixed_strings(invoke, session):
    invoke("codesearch", "-F", "wfGetDB(", "DB_REPLICA")
    assert session.calls[0]["params"]["q"] == r"wfGetDB\(\ DB_REPLICA"


def test_command_passes_repositories_and_backend(invoke, session):
    invoke("codesearch", "-b", "core", "-r", "Extension:Echo", "-r", "MediaWiki core", "x")
    assert session.calls[0]["url"].endswith("/core/api/v1/search")
    assert session.calls[0]["params"]["repos"] == "Extension:Echo,MediaWiki core"


def test_command_installed_only_shows_local_repositories(invoke, session, install: Path):
    result = invoke("--mw", str(install), "codesearch", "--installed", "getUserBlock")
    assert result.exit_code == 0
    assert "Extension:Echo" in result.output
    assert "MediaWiki core" in result.output
    assert "Other/thing" not in result.output
    assert str(install / "extensions" / "Echo") in result.output


def test_command_json(invoke, session):
    result = invoke("codesearch", "--json", "getUserBlock")
    payload = json.loads(result.stdout)
    assert payload["backend"] == "search"
    assert [repo["repo"] for repo in payload["results"]][0] == "MediaWiki core"
    assert payload["results"][1]["files"][0]["matches"][0]["number"] == 12


def test_command_exits_1_when_nothing_matches(invoke, monkeypatch):
    fake = FakeSession(FakeResponse({"Results": {}}))
    monkeypatch.setattr(CodesearchClient, "_get_session", lambda self: fake)
    result = invoke("codesearch", "nothing")
    assert result.exit_code == 1
    assert "no matches" in result.output


def test_command_reports_codesearch_errors(invoke, monkeypatch):
    fake = FakeSession(FakeResponse({"Error": "error parsing regexp"}))
    monkeypatch.setattr(CodesearchClient, "_get_session", lambda self: fake)
    result = invoke("codesearch", "(")
    assert result.exit_code == 1
    assert "codesearch: error parsing regexp" in result.output
